title: "Red Wine Quality Prediction"
author: "Nicole Bidwell, Ruocong Sun, Alysen Townsley, Hongyang Zhang"
date: "2023-12-01"
sphinx:
  config:
    bibtex_reference_style: author_year
execute:
  execute_notebooks: force 
bibtex_bibfiles:
    - references.bib