services:
  Quality-wine-env:
    image: sungg888/red-wine-quality-prediction:5b3efc5956e8
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 10G
    platform: linux/amd64 # For Mac M1/M2 chips
