# Required packages for the Group Project completed for DSCI 522.
# Perform the following command in your conda base environment:
# conda env create -f environment.yaml
name: 'red_wine_quality_prediction'
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.11.6
    - ipykernel=6.26.0
    - matplotlib=3.8.2
    - pandas=2.1.3
    - scikit-learn=1.3.2
    - requests=2.31.0
    - ipython=8.17.2
    - altair=5.1.2
    - pytest=7.4.3
    - jupyter-book
    - jupyterlab
    - click
    - seaborn=0.13.0
    - pip=23.3.1
    - notebook=6.5.4
    - jupyter_contrib_nbextensions=0.7.0
    - vl-convert-python=1.0.1

