# This environment.yaml file was adapted from the DSCI 571 fall 2023 semester environment file,
# due to the similar nature of the analysis. The original environment file was created by Varada Kolhatkar.

# Required packages for the Group Project completed for DSCI 522.
# Perform the following command in your conda base environment:
# conda env create -f environment.yaml
name: 'red_wine_quality_prediction'
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.10
    - ipykernel
    - matplotlib>=3.8.0
    - pandas>=2.1.1
    - scikit-learn>=1.3.1    
    - requests>=2.24.0
    - ipython
    - graphviz
    - python-graphviz
    - lightgbm
    - altair=5.1.2
    - vl-convert-python  # For saving altair charts as static images 
    - jinja2
    - pytest
    - pip>=23.2.1    
    - pytest=7.4.3
    - pip:
        - mglearn
        - graphviz
        - psutil>=5.7.2
